package projet.graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import projet.DAO.LocalDAO;

import myconnections.DBConnection;

public class Gestion extends javax.swing.JFrame {

    CardLayout cardl;

    /**
     * Creates new form JFrame_Projet
     */
    public Gestion() {
        initComponents();

        cardl = (CardLayout) this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("connexion invalide");
            JOptionPane.showMessageDialog(this, "connexion invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

        LocalDAO localDAO = new LocalDAO();
        localDAO.setConnection(dbConnect);

        createLocal.setLocalDAO(localDAO);
        rechercheSigleLoc.setLocalDAO(localDAO);
        rechercheDescriptionLocal.setLocalDAO(localDAO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rechercheDescriptionLocal = new projet.graph.RechercheDescriptionLocal();
        rechercheSigleLoc = new projet.graph.RechercheSigleLoc();
        createLocal = new projet.graph.CreateLocal();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLocal = new javax.swing.JMenu();
        itemCreateLoc = new javax.swing.JMenuItem();
        itemRechSigleLoc = new javax.swing.JMenuItem();
        itemRechDescLoc = new javax.swing.JMenuItem();
        menuFormateur = new javax.swing.JMenu();
        itemCreateForm = new javax.swing.JMenuItem();
        itemRechNomForm = new javax.swing.JMenuItem();
        menuCours = new javax.swing.JMenu();
        itemCreateCours = new javax.swing.JMenuItem();
        itemRechNomCours = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(rechercheDescriptionLocal, "card3");
        getContentPane().add(rechercheSigleLoc, "card4");
        getContentPane().add(createLocal, "card2");

        menuLocal.setText("Local");

        itemCreateLoc.setText("Creation local");
        itemCreateLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateLocActionPerformed(evt);
            }
        });
        menuLocal.add(itemCreateLoc);

        itemRechSigleLoc.setText("Recherche Sigle");
        itemRechSigleLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechSigleLocActionPerformed(evt);
            }
        });
        menuLocal.add(itemRechSigleLoc);

        itemRechDescLoc.setText("Recherche Desc");
        itemRechDescLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechDescLocActionPerformed(evt);
            }
        });
        menuLocal.add(itemRechDescLoc);

        jMenuBar1.add(menuLocal);

        menuFormateur.setText("Formateur");

        itemCreateForm.setText("Creation Formateur");
        itemCreateForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateFormActionPerformed(evt);
            }
        });
        menuFormateur.add(itemCreateForm);

        itemRechNomForm.setText("Recherche Nom");
        itemRechNomForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechNomFormActionPerformed(evt);
            }
        });
        menuFormateur.add(itemRechNomForm);

        jMenuBar1.add(menuFormateur);

        menuCours.setText("Cours");

        itemCreateCours.setText("Creation Cours");
        itemCreateCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCreateCoursActionPerformed(evt);
            }
        });
        menuCours.add(itemCreateCours);

        itemRechNomCours.setText("Recherche Nom");
        itemRechNomCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRechNomCoursActionPerformed(evt);
            }
        });
        menuCours.add(itemRechNomCours);

        jMenuBar1.add(menuCours);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCreateLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateLocActionPerformed
        cardl.show(this.getContentPane(), "cardCrea");
        
    }//GEN-LAST:event_itemCreateLocActionPerformed

    private void itemRechDescLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechDescLocActionPerformed
        cardl.show(this.getContentPane(), "cardRechDesc");
        
    }//GEN-LAST:event_itemRechDescLocActionPerformed

    private void itemCreateCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateCoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCreateCoursActionPerformed

    private void itemRechNomFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechNomFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRechNomFormActionPerformed

    private void itemRechSigleLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechSigleLocActionPerformed
        cardl.show(this.getContentPane(), "cardRechSigle");
        
    }//GEN-LAST:event_itemRechSigleLocActionPerformed

    private void itemCreateFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCreateFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCreateFormActionPerformed

    private void itemRechNomCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRechNomCoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRechNomCoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private projet.graph.CreateLocal createLocal;
    private javax.swing.JMenuItem itemCreateCours;
    private javax.swing.JMenuItem itemCreateForm;
    private javax.swing.JMenuItem itemCreateLoc;
    private javax.swing.JMenuItem itemRechDescLoc;
    private javax.swing.JMenuItem itemRechNomCours;
    private javax.swing.JMenuItem itemRechNomForm;
    private javax.swing.JMenuItem itemRechSigleLoc;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCours;
    private javax.swing.JMenu menuFormateur;
    private javax.swing.JMenu menuLocal;
    private projet.graph.RechercheDescriptionLocal rechercheDescriptionLocal;
    private projet.graph.RechercheSigleLoc rechercheSigleLoc;
    // End of variables declaration//GEN-END:variables
}
