/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.graph;

import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projet.DAO.CoursDAO;
import projet.metier.Cours;

/**
 *
 * @author Florence
 */
public class RechercheMatiereCours extends javax.swing.JPanel {

    CoursDAO coursDAO = null;
    DefaultTableModel dft1 = new DefaultTableModel();
    public RechercheMatiereCours() {
        initComponents();
        dft1.addColumn("idcours");
        dft1.addColumn("matiere");
        dft1.addColumn("heures");
        
        tabRechPartCours.setModel(dft1);
        
    }

    public void setCoursDAO(CoursDAO coursDAO) {
        this.coursDAO = coursDAO;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRechPartMAt = new javax.swing.JLabel();
        lbRech = new javax.swing.JLabel();
        txtRechPartMAt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabRechPartCours = new javax.swing.JTable();
        btRechPartCours = new javax.swing.JButton();

        lbRechPartMAt.setText("Recherche partielle via matiere");

        lbRech.setText("Matiere : ");

        txtRechPartMAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechPartMAtActionPerformed(evt);
            }
        });

        tabRechPartCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idcours", "matiere", "heures"
            }
        ));
        jScrollPane1.setViewportView(tabRechPartCours);

        btRechPartCours.setText("Chercher");
        btRechPartCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRechPartCoursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRech)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRechPartMAt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btRechPartCours))
                    .addComponent(lbRechPartMAt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRechPartMAt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRech)
                    .addComponent(txtRechPartMAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRechPartCours))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechPartMAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechPartMAtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechPartMAtActionPerformed

    private void btRechPartCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRechPartCoursActionPerformed
        try {
            String matrech = txtRechPartMAt.getText();
            System.out.println("matrech");
            List<Cours> cours = coursDAO.rechMatiere(matrech);
            int nr = dft1.getRowCount();
            for (int i = nr - 1; i >= 0; i--) {
                dft1.removeRow(i);
            }
            for (Cours co : cours) {

                Vector v = new Vector();
                v.add(co.getIdcours());
                v.add(co.getMatiere());
                v.add(co.getHeures());
                dft1.addRow(v);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btRechPartCoursActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRechPartCours;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbRech;
    private javax.swing.JLabel lbRechPartMAt;
    private javax.swing.JTable tabRechPartCours;
    private javax.swing.JTextField txtRechPartMAt;
    // End of variables declaration//GEN-END:variables
}
